version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependabot
      - actions
    open-pull-requests-limit: 10
    reviewers:
      - ncalteen
    groups:
      actions:
        update-types:
          - major
          - minor
          - patch
