name: Lint Codebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: write
  packages: read
  pull-requests: write
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Codebase
        id: lint
        uses: oxsecurity/megalinter/flavors/javascript@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
